name: Deploy to cPanel Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to cPanel (Tests Skipped)
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install PHP Dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction
    
    - name: Install NPM Dependencies
      run: npm ci
    
    - name: Build Assets
      run: npm run build
    
    - name: Create deployment package
      run: |
        mkdir -p island-tours-deploy
        
        # Copy only essential application files (exclude heavy folders)
        cp -r app island-tours-deploy/
        cp -r bootstrap island-tours-deploy/
        cp -r config island-tours-deploy/
        cp -r database island-tours-deploy/
        cp -r public island-tours-deploy/
        cp -r resources island-tours-deploy/
        cp -r routes island-tours-deploy/
        cp -r storage island-tours-deploy/
        
        # Copy essential files
        cp artisan island-tours-deploy/
        cp composer.json island-tours-deploy/
        cp composer.lock island-tours-deploy/
        
        # Install production dependencies in deployment folder
        cd island-tours-deploy
        composer install --no-dev --optimize-autoloader --no-interaction
        
        # Set proper permissions
        chmod -R 755 storage/
        chmod -R 755 bootstrap/cache/
    
    - name: Deploy to cPanel via FTP (Alternative Method)
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: './island-tours-deploy/'
        remoteDir: ${{ secrets.FTP_PATH }}
        options: '--transfer-all --delete --verbose'
